### ISSUE TITLE
Add a feature for setting and saving a default theme for the editor. 

### ISSUE THREAD

**Issue by SethWalkeroo** [SethWalkeroo/Quiet-Text#81] opened 2020-10-14 09:08 UTC
There is a default theme already in the theme configs, but it never changes. It would be cool if the user didn't have to reset their theme every time they reloaded the editor.

**Comment by zer0link** [comment] 2020-10-14 09:15
Hi, this seems like an interesting issue, can you please assign to me so I work on that?

**Comment by SethWalkeroo** [comment] 2020-10-14 09:17
@zer0link for sure, message me if you have any difficulties. The feature is brand new and I haven't fully thought out how it will be continually integrated.

**Comment by zer0link** [comment] 2020-10-14 09:41
Thanks for the assignment, @SethWalkeroo ,
I tried to run the steps in [readme](https://github.com/SethWalkeroo/Quiet-Text/blob/main/README.md), and I played around with the color schemes and restarting the editor a couple of times. It seems to remember the last color scheme I am using.
Maybe I misunderstood the issue here, can you show me a step by step to reproduce the issue?

**Comment by SethWalkeroo** [comment] 2020-10-14 09:59
@zer0link Oh, looks like there is a problem with loading the default theme. If you open up the editor again and try entering some syntax, you will notice that the syntax is in the theme of Gruvbox, which is the default theme at the moment. I forgot to initialize the rest of the theme, I will work on that now.

**Comment by SethWalkeroo** [comment] 2020-10-14 10:22
@zer0link Alright, the default theme should load up the same every time you launch the editor now.

**Comment by zer0link** [comment] 2020-10-14 12:20
Yes, I can see everytime I restarted the editor, it uses the default theme (Gruvbox)

**Comment by SethWalkeroo** [comment] 2020-10-14 15:00
I just realized how dumb it is to have a default theme when the theme saves all by itself. Forget this issue. I don't know where my head was at.

**Closed as completed** 2020-10-18 17:01 UTC
Labels: enhancement, Hacktoberfest

**Comment by zer0link** [comment] 2020-10-18 19:41
Hi, can I know if the issue is still open?

**Comment by SethWalkeroo** [comment] 2020-10-18 19:49
@zer0link No, sorry, this issue is now closed. I've added the default theme setting to the editor.
